[env:magtag]
platform = espressif32
board = adafruit_magtag29_esp32s2
framework = arduino

lib_deps =
    adafruit/Adafruit SCD30@^1.0.9
    adafruit/Adafruit NeoPixel@^1.12.3
    adafruit/Adafruit EPD@^4.5.5
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit BusIO@^1.16.1
    adafruit/Adafruit LIS3DH@^1.2.6

monitor_speed = 115200
upload_speed = 921600
